import { Country } from "./country.model";

export const countries: Country[] = [
  {
    name: "Afghanistan",
    code: "AF",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Åland Islands",
    code: "AX",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Albania",
    code: "AL",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Algeria",
    code: "DZ",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: undefined,
  },
  {
    name: "American Samoa",
    code: "AS",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "Andorra",
    code: "AD",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Angola",
    code: "AO",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  {
    name: "Anguilla",
    code: "AI",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Antarctica",
    code: "AQ",
    region: undefined,
    subRegion: undefined,
    intermediateRegion: undefined,
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Argentina",
    code: "AR",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Armenia",
    code: "AM",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Aruba",
    code: "AW",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Australia",
    code: "AU",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: undefined,
  },
  {
    name: "Austria",
    code: "AT",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Bahamas",
    code: "BS",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Bahrain",
    code: "BH",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Bangladesh",
    code: "BD",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Barbados",
    code: "BB",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Belarus",
    code: "BY",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Belgium",
    code: "BE",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Belize",
    code: "BZ",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  {
    name: "Benin",
    code: "BJ",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Bermuda",
    code: "BM",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: undefined,
  },
  {
    name: "Bhutan",
    code: "BT",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Bolivia (Plurinational State of)",
    code: "BO",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    code: "BQ",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Botswana",
    code: "BW",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  {
    name: "Bouvet Island",
    code: "BV",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Brazil",
    code: "BR",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Brunei Darussalam",
    code: "BN",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Bulgaria",
    code: "BG",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Burkina Faso",
    code: "BF",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Burundi",
    code: "BI",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Cabo Verde",
    code: "CV",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Cambodia",
    code: "KH",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Cameroon",
    code: "CM",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  {
    name: "Canada",
    code: "CA",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: undefined,
  },
  {
    name: "Cayman Islands",
    code: "KY",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Central African Republic",
    code: "CF",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  {
    name: "Chad",
    code: "TD",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  {
    name: "Chile",
    code: "CL",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "China",
    code: "CN",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Christmas Island",
    code: "CX",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: undefined,
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: undefined,
  },
  {
    name: "Colombia",
    code: "CO",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Comoros",
    code: "KM",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Congo",
    code: "CG",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  {
    name: "Congo, Democratic Republic of the",
    code: "CD",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  {
    name: "Cook Islands",
    code: "CK",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "Costa Rica",
    code: "CR",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Croatia",
    code: "HR",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Cuba",
    code: "CU",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Curaçao",
    code: "CW",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Cyprus",
    code: "CY",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Czechia",
    code: "CZ",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Denmark",
    code: "DK",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Djibouti",
    code: "DJ",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Dominica",
    code: "DM",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Ecuador",
    code: "EC",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Egypt",
    code: "EG",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: undefined,
  },
  {
    name: "El Salvador",
    code: "SV",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  {
    name: "Eritrea",
    code: "ER",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Estonia",
    code: "EE",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Eswatini",
    code: "SZ",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  {
    name: "Ethiopia",
    code: "ET",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Fiji",
    code: "FJ",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: undefined,
  },
  {
    name: "Finland",
    code: "FI",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "France",
    code: "FR",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: undefined,
  },
  {
    name: "French Guiana",
    code: "GF",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "French Polynesia",
    code: "PF",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "French Southern Territories",
    code: "TF",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Gabon",
    code: "GA",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  {
    name: "Gambia",
    code: "GM",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Georgia",
    code: "GE",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Germany",
    code: "DE",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Ghana",
    code: "GH",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Gibraltar",
    code: "GI",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Greece",
    code: "GR",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Greenland",
    code: "GL",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: undefined,
  },
  {
    name: "Grenada",
    code: "GD",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Guam",
    code: "GU",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: undefined,
  },
  {
    name: "Guatemala",
    code: "GT",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  {
    name: "Guernsey",
    code: "GG",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "Channel Islands",
  },
  {
    name: "Guinea",
    code: "GN",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Guyana",
    code: "GY",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Haiti",
    code: "HT",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Heard Island and McDonald Islands",
    code: "HM",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: undefined,
  },
  {
    name: "Holy See",
    code: "VA",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Honduras",
    code: "HN",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  {
    name: "Hong Kong",
    code: "HK",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Hungary",
    code: "HU",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Iceland",
    code: "IS",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "India",
    code: "IN",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Indonesia",
    code: "ID",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Iran (Islamic Republic of)",
    code: "IR",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Iraq",
    code: "IQ",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Ireland",
    code: "IE",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Isle of Man",
    code: "IM",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Israel",
    code: "IL",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Italy",
    code: "IT",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Jamaica",
    code: "JM",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Japan",
    code: "JP",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Jersey",
    code: "JE",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: "Channel Islands",
  },
  {
    name: "Jordan",
    code: "JO",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Kenya",
    code: "KE",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Kiribati",
    code: "KI",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: undefined,
  },
  {
    name: "Korea (Democratic People's Republic of)",
    code: "KP",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Korea, Republic of",
    code: "KR",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Kuwait",
    code: "KW",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Lao People's Democratic Republic",
    code: "LA",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Latvia",
    code: "LV",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Lebanon",
    code: "LB",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Lesotho",
    code: "LS",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  {
    name: "Liberia",
    code: "LR",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Libya",
    code: "LY",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: undefined,
  },
  {
    name: "Liechtenstein",
    code: "LI",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Lithuania",
    code: "LT",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Luxembourg",
    code: "LU",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Macao",
    code: "MO",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Madagascar",
    code: "MG",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Malawi",
    code: "MW",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Malaysia",
    code: "MY",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Maldives",
    code: "MV",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Mali",
    code: "ML",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Malta",
    code: "MT",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Marshall Islands",
    code: "MH",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: undefined,
  },
  {
    name: "Martinique",
    code: "MQ",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Mauritania",
    code: "MR",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Mauritius",
    code: "MU",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Mayotte",
    code: "YT",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Mexico",
    code: "MX",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  {
    name: "Micronesia (Federated States of)",
    code: "FM",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: undefined,
  },
  {
    name: "Moldova, Republic of",
    code: "MD",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Monaco",
    code: "MC",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Mongolia",
    code: "MN",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Montenegro",
    code: "ME",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Montserrat",
    code: "MS",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Morocco",
    code: "MA",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: undefined,
  },
  {
    name: "Mozambique",
    code: "MZ",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Myanmar",
    code: "MM",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Namibia",
    code: "NA",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  {
    name: "Nauru",
    code: "NR",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: undefined,
  },
  {
    name: "Nepal",
    code: "NP",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Netherlands",
    code: "NL",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: undefined,
  },
  {
    name: "New Caledonia",
    code: "NC",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: undefined,
  },
  {
    name: "New Zealand",
    code: "NZ",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: undefined,
  },
  {
    name: "Nicaragua",
    code: "NI",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  {
    name: "Niger",
    code: "NE",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Nigeria",
    code: "NG",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Niue",
    code: "NU",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "Norfolk Island",
    code: "NF",
    region: "Oceania",
    subRegion: "Australia and New Zealand",
    intermediateRegion: undefined,
  },
  {
    name: "North Macedonia",
    code: "MK",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: undefined,
  },
  {
    name: "Norway",
    code: "NO",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Oman",
    code: "OM",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Pakistan",
    code: "PK",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Palau",
    code: "PW",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: undefined,
  },
  {
    name: "Palestine, State of",
    code: "PS",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Panama",
    code: "PA",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Central America",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: undefined,
  },
  {
    name: "Paraguay",
    code: "PY",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Peru",
    code: "PE",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Philippines",
    code: "PH",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Pitcairn",
    code: "PN",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "Poland",
    code: "PL",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Portugal",
    code: "PT",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Puerto Rico",
    code: "PR",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Qatar",
    code: "QA",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Réunion",
    code: "RE",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Romania",
    code: "RO",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Russian Federation",
    code: "RU",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Rwanda",
    code: "RW",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Saint Barthélemy",
    code: "BL",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Saint Martin (French part)",
    code: "MF",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: undefined,
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Samoa",
    code: "WS",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "San Marino",
    code: "SM",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Middle Africa",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Senegal",
    code: "SN",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Serbia",
    code: "RS",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Seychelles",
    code: "SC",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Singapore",
    code: "SG",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Sint Maarten (Dutch part)",
    code: "SX",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Slovakia",
    code: "SK",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Slovenia",
    code: "SI",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Solomon Islands",
    code: "SB",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: undefined,
  },
  {
    name: "Somalia",
    code: "SO",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "South Africa",
    code: "ZA",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Southern Africa",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "South Sudan",
    code: "SS",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Spain",
    code: "ES",
    region: "Europe",
    subRegion: "Southern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Sri Lanka",
    code: "LK",
    region: "Asia",
    subRegion: "Southern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Sudan",
    code: "SD",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: undefined,
  },
  {
    name: "Suriname",
    code: "SR",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Sweden",
    code: "SE",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Switzerland",
    code: "CH",
    region: "Europe",
    subRegion: "Western Europe",
    intermediateRegion: undefined,
  },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Taiwan, Province of China",
    code: "TW",
    region: "Asia",
    subRegion: "Eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Tajikistan",
    code: "TJ",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Tanzania, United Republic of",
    code: "TZ",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Thailand",
    code: "TH",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Timor-Leste",
    code: "TL",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Togo",
    code: "TG",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Western Africa",
  },
  {
    name: "Tokelau",
    code: "TK",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "Tonga",
    code: "TO",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Tunisia",
    code: "TN",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: undefined,
  },
  {
    name: "Turkey",
    code: "TR",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Turkmenistan",
    code: "TM",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Tuvalu",
    code: "TV",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "Uganda",
    code: "UG",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Ukraine",
    code: "UA",
    region: "Europe",
    subRegion: "Eastern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    code: "GB",
    region: "Europe",
    subRegion: "Northern Europe",
    intermediateRegion: undefined,
  },
  {
    name: "United States of America",
    code: "US",
    region: "Americas",
    subRegion: "Northern America",
    intermediateRegion: undefined,
  },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    region: "Oceania",
    subRegion: "Micronesia",
    intermediateRegion: undefined,
  },
  {
    name: "Uruguay",
    code: "UY",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    region: "Asia",
    subRegion: "Central Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Vanuatu",
    code: "VU",
    region: "Oceania",
    subRegion: "Melanesia",
    intermediateRegion: undefined,
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    code: "VE",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "South America",
  },
  {
    name: "Viet Nam",
    code: "VN",
    region: "Asia",
    subRegion: "South-eastern Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Virgin Islands (British)",
    code: "VG",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Virgin Islands (U.S.)",
    code: "VI",
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
    intermediateRegion: "Caribbean",
  },
  {
    name: "Wallis and Futuna",
    code: "WF",
    region: "Oceania",
    subRegion: "Polynesia",
    intermediateRegion: undefined,
  },
  {
    name: "Western Sahara",
    code: "EH",
    region: "Africa",
    subRegion: "Northern Africa",
    intermediateRegion: undefined,
  },
  {
    name: "Yemen",
    code: "YE",
    region: "Asia",
    subRegion: "Western Asia",
    intermediateRegion: undefined,
  },
  {
    name: "Zambia",
    code: "ZM",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
    intermediateRegion: "Eastern Africa",
  },
];
