create table
  public.suggestions (
    id bigint generated by default as identity not null,
    artist_name text not null,
    country_code bigint null,
    constraint suggestions_pkey primary key (id)
  ) tablespace pg_default;